---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt: 
        upgrade: true
        update_cache: yes
      register: output

    - debug:
       msg: "{{ output.stdout_lines }}"
