---
- name: Update apt packages
  hosts: servers
  become: true
  tasks:
    - name: update apt packages
      apt: 
        upgrade: true
        update_cache: yes
      register: output
      
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      
    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
      
    - debug:
       msg: "{{ output.stdout_lines }}"
