---
- name: Update apt packages
  hosts: servers
  become: true
  tasks:
    - name: Update apt packages
      apt: 
        upgrade: true
        update_cache: yes
      register: output

    - name: Update apt package debug
      debug:
        msg: "{{ output }}"
      
    - name: Update pihole
      when: inventory_hostname in groups['piholes']
      command: "pihole -up"
      register: output

    - name: Update pihole debug
      debug:
        msg: "{{ output }}"
      
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      
    - name: Sending an e-mail if reboot needed
      when: reboot_required_file.stat.exists == false
      mail:
        host: "{{ var_gmail_smtp_server }}"
        port: "{{ var_gmail_smtp_port }}"
        username: "{{ var_gmail_sender }}"
        password: "{{ var_gmail_password }}"
        to: "{{ var_gmail_receiver }}"
        subject: Server Reboot requited - Ansible 
        body: Reboot requied for systems "{{ ansible_hostname }}".
      delegate_to: 127.0.0.1
